# Generated by Django 4.0.5 on 2023-09-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_post_options_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
